# # Transparent background
# set -g status-style bg=default
#
# # Center the window list
# set -g status-justify centre

# Subtle grey background
set -g status-style bg=colour236,fg=colour250

# Clear left and right sections
set -g status-left ''
set -g status-right ''

# Center the window list
set -g status-justify centre
