# Status bar position

set -g status-position top

# Keep default status bar colors (black bg, green/white text)
set -g status-style 'bg=black fg=green'
set -g status-style 'bg=black fg=green'

# Regular windows — default look, with extra padding around the name
set -g window-status-format ' #W '

# Active window — highlighted with reverse video (standout), extra padding
# set -g window-status-current-format ' #I:  #W  '
set -g window-status-current-format ' • #W  '
# set -g window-status-current-format '   •   '
set -g window-status-current-style 'bg=blue fg=black bold'

# Allow window names to grow as long as needed without truncation
set -g window-status-separator '  '
setw -g automatic-rename off
set -g status-left-length 200
set -g status-right-length 200

set -g status-right-length 200
set -g status-right '#(acpi | cut -d, -f2) |  #{pane_current_path} '

# hide tmux bar, hit ctr-b twice to toggle
set -g status off
bind-key C-b set-option status


# Move current window left/right
bind -n M-Left swap-window -t -1
bind -n M-Right swap-window -t +1
